### ISSUE TITLE
Groupes: impossible de configurer sa propre description

### ISSUE THREAD

**Issue by r0one** [NastuzziSamy/emploidutemps#1]
Il est possible d'éditer la description des autres, soit au moment de l'ajout, soit en affichant la liste des membres.

En revanche, on ne peut s'ajouter à un groupe (ce qui est logique: soit on le crée, soit on y est ajouté par quelqu'un d'autre) et la liste des membres n'affiche pas son propre nom (ce qui est logique: si on peut voir les membres, c'est qu'on y appartient). Mais du coup il est impossible d'éditer sa propre description.

Je sais pas si j'ai été clair, hésite(z) pas à demander des détails.

**Comment by NastuzziSamy** [comment]
@CdRom1, j'ai prévu une v3 pour emploidut d'ici la rentrée de printemps, pour intégrer le nouveau Portail. La gestion des groupes est donc déportée et plus gérée de la même manière
