### ISSUE TITLE
[Prévoir] Nouveau lien horaires prévisionnelles

### ISSUE THREAD

**Issue by el-wynn** [NastuzziSamy/emploidutemps#5]
Salut! 

L'application d'inscription des UV étant fermée, le lien depuis la fonction de prévision n'est plus d'aucune utilité (https://webapplis.utc.fr/smeappli/inscriptions/index.xhtml)

Je suggère d'utiliser le lien vers le testeur de compatibilité à la place
https://webapplis.utc.fr/smeappli/testuvsetu/index.xhtml

(Excellente mise à jour au passage)

**Comment by NastuzziSamy** [comment]
Merci pour ton retour @el-wynn !

Je pense qu'on devrait mettre les deux liens ! :) 

@artemisart je te laisse gérer ^^

**Comment by artemisart** [comment]
Yep, la version originale https://codepen.io/artemisart/full/LMaQYq l'intègre déjà donc ça sera rapide.

**Comment by artemisart** [comment]
J'ai push 6a77cfc0273aa324806e1c692b272a04f199345a
